/*
 * Full-window screenshots (1440×900) of each screen, for visual review.
 * Written to e2e/__screens__/ (gitignored).
 */
import path from "node:path";
import type { Page } from "@playwright/test";
import { artifactHtml, expect, MOD, test, today } from "./fixtures";

const SCREENS = path.join(import.meta.dirname, "__screens__");
const shot = (page: Page, name: string) => page.screenshot({ path: path.join(SCREENS, `${name}.png`) });

/** Skeletons inside the window: cards past the preload margin keep theirs until they scroll near. */
const skeletonsOnScreen = (page: Page) =>
  page.evaluate(() =>
    [...document.querySelectorAll("[data-testid=doc-skeleton]")].filter((el) => {
      const r = el.getBoundingClientRect();
      return r.right > 0 && r.left < innerWidth && r.bottom > 0 && r.top < innerHeight;
    }).length,
  );

/** Moves the pointer off the cards and waits until every preview in the window has loaded (no skeleton left) and faded in. */
async function settle(page: Page) {
  await page.mouse.move(110, 760); // an empty spot in the sidebar
  await expect.poll(() => skeletonsOnScreen(page), { timeout: 15_000 }).toBe(0);
  await page.waitForTimeout(500);
}

/** A report-like page (kicker, title, three stats, a bar chart), so previews look like real artifacts. */
function reportHtml(title: string, kicker: string, accent: string, stats: [string, string][], bars: number[]): string {
  const stat = ([v, l]: [string, string]) => `<div class="s"><b>${v}</b><span>${l}</span></div>`;
  const bar = (h: number) => `<i style="height:${h}%"></i>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${title}</title>
<style>body{font-family:-apple-system,system-ui,sans-serif;margin:0;padding:56px 64px;color:#1d1d1f;background:#fff}
.k{font:600 15px/1 ui-monospace,monospace;letter-spacing:.08em;text-transform:uppercase;color:${accent}}
h1{font-size:52px;letter-spacing:-.02em;margin:18px 0 36px}.row{display:flex;gap:20px;margin-bottom:40px}
.s{flex:1;border:1px solid #e5e5e5;border-radius:16px;padding:22px 24px}.s b{display:block;font-size:40px;color:${accent}}
.s span{font-size:18px;color:#6a6a6a}.c{display:flex;align-items:flex-end;gap:18px;height:300px;border-bottom:2px solid #eee}
.c i{flex:1;border-radius:10px 10px 0 0;background:${accent};opacity:.85}p{font-size:22px;line-height:1.6;color:#555}</style></head>
<body><div class="k">${kicker}</div><h1>${title}</h1><div class="row">${stats.map(stat).join("")}</div>
<div class="c">${bars.map(bar).join("")}</div><p>Generated by an agent and dropped into a room.</p></body></html>`;
}

test("screens for visual review", async ({ page, daemon }) => {
  test.setTimeout(90_000); // eight live previews must load before each shot
  const date = today();
  await daemon.createRoom("Benchmarks");
  await daemon.createRoom("Design system");
  await daemon.createRoom("Research");
  const docs: [string, string, string, [string, string][], number[]][] = [
    ["Latency comparison", "Benchmark · 3 runtimes", "#3b6fd8", [["42 ms", "p50"], ["118 ms", "p95"], ["−18%", "vs last week"]], [70, 55, 82, 40, 63]],
    ["Memory usage", "Heap snapshots", "#2f9e6e", [["212 MB", "peak"], ["148 MB", "steady"], ["3", "leaks fixed"]], [45, 60, 52, 38, 30]],
    ["Weekly report", "Week 40", "#c9781a", [["2", "regressions"], ["3", "wins"], ["14", "PRs merged"]], [30, 48, 66, 72, 90]],
    ["Cold start", "First request", "#8a4fd0", [["1.4 s", "cold"], ["0.3 s", "warm"], ["−0.6 s", "this sprint"]], [90, 74, 60, 51, 44]],
    ["Bundle size", "Web client", "#d14b6a", [["412 KB", "gzip"], ["−9%", "since v2"], ["38", "chunks"]], [80, 76, 70, 66, 61]],
    ["Error budget", "SLO · 30 days", "#1f8a8a", [["99.94%", "uptime"], ["26 min", "left"], ["1", "incident"]], [20, 35, 25, 60, 15]],
  ];
  for (const [i, [title, kicker, accent, stats, bars]] of docs.entries()) {
    await daemon.write(`Benchmarks/doc-${i + 1}.html`, reportHtml(title, kicker, accent, stats, bars));
    await new Promise((r) => setTimeout(r, 30)); // distinct createdAt, oldest first
  }
  await daemon.write("Design-system/tokens.html", reportHtml("Color tokens", "Design system", "#ff385c", [["12", "tokens"], ["2", "themes"], ["AA", "contrast"]], [60, 40, 80]));
  await daemon.write(`journal/${date}/dream.html`, reportHtml("Yesterday in review", "Dream", "#444444", [["3", "rooms"], ["8", "new docs"], ["2", "notes"]], [40, 70, 55]));
  await daemon.saveNote(date, "Plan", "- Read the weekly benchmark report\n- Clean up the color tokens");
  await daemon.saveNote(date, "Review", "Finished the latency report today.");

  await page.goto("/");
  const rooms = page.getByRole("list", { name: "Rooms" });

  // Room strip with 3+ cards.
  await rooms.getByRole("button", { name: "Benchmarks" }).click();
  await expect(page.getByTestId("artifact-card")).toHaveCount(6);
  await settle(page);
  await shot(page, "room-strip");

  // Empty room.
  await rooms.getByRole("button", { name: "Research" }).click();
  await expect(page.getByText("No artifacts yet")).toBeVisible();
  await settle(page);
  await shot(page, "empty-room");

  // Journal: dream, a room artifact, two notes.
  await page.getByRole("button", { name: "Journal", exact: true }).click();
  await expect(page.getByRole("list", { name: "Your day" }).getByTestId("day-artifact")).toHaveCount(8);
  await expect(page.getByRole("list", { name: "Your day" }).getByRole("button", { name: "Review", exact: true })).toBeVisible();
  await settle(page);
  await shot(page, "journal");

  // Note tab.
  await page.getByRole("list", { name: "Your day" }).getByRole("button", { name: "Plan" }).click();
  await expect(page.getByRole("textbox", { name: "Note" })).toHaveValue(/weekly benchmark report/);
  await settle(page);
  await shot(page, "note-tab");

  // Collapsed sidebar (on a room, so the strip shows at full width).
  await rooms.getByRole("button", { name: "Benchmarks" }).click();
  await page.keyboard.press(`${MOD}+b`);
  await expect(page.getByRole("button", { name: "Show sidebar (⌘B)" })).toBeVisible();
  await settle(page);
  await shot(page, "collapsed-sidebar");
  await page.keyboard.press(`${MOD}+b`);
  await expect(page.getByRole("button", { name: "Hide sidebar (⌘B)" })).toBeVisible();
  await settle(page);

  // QuickFind open, with a query that hits a room and documents.
  await page.keyboard.press(`${MOD}+k`);
  const input = page.getByPlaceholder("Find a room or artifact");
  await expect(input).toBeVisible();
  await input.fill("report");
  await expect(page.getByRole("option", { name: /Weekly report/ })).toBeVisible();
  await page.waitForTimeout(300); // dialog open animation
  await shot(page, "quickfind");
});
