[package]
name = "roomsd"
edition.workspace = true
version.workspace = true

[dependencies]
rooms-protocol = { path = "../rooms-protocol" }
rooms-core = { path = "../rooms-core" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
axum = "0.8"
tower-http = { version = "0.6", features = ["set-header", "cors"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["io"] }
futures = "0.3"
nanoid = "0.4"
dirs = "5"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
tempfile = "3"
http-body-util = "0.1"
